#! /bin/bash
set -x
### BEGIN INIT INFO
# Provides:          honeyPot
# Should-Start:      
# Required-Start:    $local_fs 
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: honey pot for various services
# Description:       Debian init script for the HoneyPot
### END INIT INFO

###Vars /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/
logfile='honeyPi.log'
logfolder='/var/log/honeyPi'
logFile='$logfolder/$logfile'
honeyPATH=''
###Funcs ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
log_chk(){
	if [ ! -e $logfolder ];then
		mkdir $logfolder -m 775
			if [ ! -e $logfile ];then
				touch $logfile
			fi
	fi
	}

honey_start(){
	
	}

honey_stop(){
	
	
	}

honey_restart(){
	
	
	}

honey_status(){
		sts_glastopf=`ps aux |grep glastopf >> /dev/null;echo $?`
		sts_dionaea=`ps aux | grep dionaea >> /dev/null;echo $?`
		sts_ragpicker=`ps aux| grep ragpicker >> /dev/null;echo $?`
		sts_honssh=`ps aux |grep honssh >> /dev/null; echo $?`
		sts_kippo=`ps aux|grep kippo >>/dev/null ;echo $?`
		
		if [ "$sts_glastopf" == '0' ];then
			echo " "
			exit 1
		fi
		if [ "$sts_glastopf" == '0' ];then
			echo " "
			exit 1
		fi
		if [ "$sts_glastopf" == '0' ];then
			echo " "
			exit 1
		fi
		if [ "$sts_glastopf" == '0' ];then
			echo " "
			exit 1
		fi
		if [ "$sts_glastopf" == '0' ];then
			echo " "
			exit 1
		fi
		if [ "$sts_glastopf" == '0' ];then
			echo " "
			exit 1
		fi
	}
###
#Main- _ - _ - _ - _ - _ - _ -_ - _ - _ - _ - _ - _ - _ - _ - _ - _ - _ -
###
 log_chk
	case "$1" in
		start	) honey_start ;;
		stop	)  honey_stop ;;
		restart	) honey_stop;honey_start;;
		*		) " Usage: init_honeyPi [start|stop|status]"
